-- AlterEnum
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'EMPTY_SEAT_CHARGE';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'UNAUTHORIZED_CARGO_CHARGE';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'REFUSED_POSTED_FARE';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'OTHER_FARE_DISPUTE';