// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/coordinate-verification" | "/admin/discount-cards" | "/admin/incidents" | "/admin/reports" | "/admin/users" | "/auth" | "/auth/request-reset" | "/auth/reset-password" | "/calculator" | "/dashboard" | "/dashboard/calculator" | "/dashboard/incidents" | "/dashboard/profile" | "/dashboard/report" | "/encoder" | "/encoder/permits" | "/encoder/vehicles" | "/encoder/vehicles/new" | "/enforcer" | "/enforcer/incidents" | "/features" | "/history" | "/login" | "/profile" | "/profile/discount" | "/report"
type AppRouteHandlerRoutes = "/[slug]" | "/api/admin/discount-cards" | "/api/admin/discount-cards/create" | "/api/admin/incidents/stats" | "/api/admin/locations" | "/api/admin/locations/[id]" | "/api/admin/locations/validate" | "/api/admin/reports" | "/api/admin/reset-password" | "/api/admin/storage" | "/api/admin/users" | "/api/admin/users/create" | "/api/admin/users/pending" | "/api/admin/users/toggle-status" | "/api/admin/users/verify" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/auth/request-reset" | "/api/auth/reset-password" | "/api/auth/verify-otp" | "/api/dashboard/activity" | "/api/dashboard/stats" | "/api/discount-cards/apply" | "/api/discount-cards/me" | "/api/discount-cards/my-application" | "/api/discount-cards/validate-id" | "/api/evidence/[evidenceId]/review" | "/api/fare-calculations" | "/api/geocode/forward" | "/api/geocode/reverse" | "/api/health" | "/api/incidents" | "/api/incidents/[incidentId]/evidence" | "/api/incidents/[incidentId]/issue-ticket" | "/api/incidents/[incidentId]/resolve" | "/api/incidents/[incidentId]/take" | "/api/incidents/enforcer" | "/api/incidents/report" | "/api/locations" | "/api/permits" | "/api/permits/[id]" | "/api/permits/[id]/renew" | "/api/routes" | "/api/routes/calculate" | "/api/test-coordinates" | "/api/tickets" | "/api/tracker/segment" | "/api/user/profile" | "/api/users" | "/api/vehicles" | "/api/vehicles/[id]" | "/api/vehicles/options" | "/api/violations/history/[plateNumber]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/admin/coordinate-verification": {}
  "/admin/discount-cards": {}
  "/admin/incidents": {}
  "/admin/reports": {}
  "/admin/users": {}
  "/api/admin/discount-cards": {}
  "/api/admin/discount-cards/create": {}
  "/api/admin/incidents/stats": {}
  "/api/admin/locations": {}
  "/api/admin/locations/[id]": { "id": string; }
  "/api/admin/locations/validate": {}
  "/api/admin/reports": {}
  "/api/admin/reset-password": {}
  "/api/admin/storage": {}
  "/api/admin/users": {}
  "/api/admin/users/create": {}
  "/api/admin/users/pending": {}
  "/api/admin/users/toggle-status": {}
  "/api/admin/users/verify": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/auth/request-reset": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify-otp": {}
  "/api/dashboard/activity": {}
  "/api/dashboard/stats": {}
  "/api/discount-cards/apply": {}
  "/api/discount-cards/me": {}
  "/api/discount-cards/my-application": {}
  "/api/discount-cards/validate-id": {}
  "/api/evidence/[evidenceId]/review": { "evidenceId": string; }
  "/api/fare-calculations": {}
  "/api/geocode/forward": {}
  "/api/geocode/reverse": {}
  "/api/health": {}
  "/api/incidents": {}
  "/api/incidents/[incidentId]/evidence": { "incidentId": string; }
  "/api/incidents/[incidentId]/issue-ticket": { "incidentId": string; }
  "/api/incidents/[incidentId]/resolve": { "incidentId": string; }
  "/api/incidents/[incidentId]/take": { "incidentId": string; }
  "/api/incidents/enforcer": {}
  "/api/incidents/report": {}
  "/api/locations": {}
  "/api/permits": {}
  "/api/permits/[id]": { "id": string; }
  "/api/permits/[id]/renew": { "id": string; }
  "/api/routes": {}
  "/api/routes/calculate": {}
  "/api/test-coordinates": {}
  "/api/tickets": {}
  "/api/tracker/segment": {}
  "/api/user/profile": {}
  "/api/users": {}
  "/api/vehicles": {}
  "/api/vehicles/[id]": { "id": string; }
  "/api/vehicles/options": {}
  "/api/violations/history/[plateNumber]": { "plateNumber": string; }
  "/auth": {}
  "/auth/request-reset": {}
  "/auth/reset-password": {}
  "/calculator": {}
  "/dashboard": {}
  "/dashboard/calculator": {}
  "/dashboard/incidents": {}
  "/dashboard/profile": {}
  "/dashboard/report": {}
  "/encoder": {}
  "/encoder/permits": {}
  "/encoder/vehicles": {}
  "/encoder/vehicles/new": {}
  "/enforcer": {}
  "/enforcer/incidents": {}
  "/features": {}
  "/history": {}
  "/login": {}
  "/profile": {}
  "/profile/discount": {}
  "/report": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
