// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/coordinate-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coordinate-verification">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coordinate-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/discount-cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/discount-cards">> = Specific
  const handler = {} as typeof import("../../src/app/admin/discount-cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/admin/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/request-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/request-reset">> = Specific
  const handler = {} as typeof import("../../src/app/auth/request-reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calculator">> = Specific
  const handler = {} as typeof import("../../src/app/calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calculator">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/report">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/encoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/encoder">> = Specific
  const handler = {} as typeof import("../../src/app/encoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/encoder/permits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/encoder/permits">> = Specific
  const handler = {} as typeof import("../../src/app/encoder/permits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/encoder/vehicles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/encoder/vehicles/new">> = Specific
  const handler = {} as typeof import("../../src/app/encoder/vehicles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/encoder/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/encoder/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/encoder/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/enforcer/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enforcer/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/enforcer/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/enforcer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enforcer">> = Specific
  const handler = {} as typeof import("../../src/app/enforcer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../src/app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/discount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/discount">> = Specific
  const handler = {} as typeof import("../../src/app/profile/discount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../src/app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/discount-cards/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/discount-cards/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/discount-cards/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/discount-cards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/discount-cards">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/discount-cards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/incidents/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/incidents/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/incidents/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/locations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/locations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/locations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/locations">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/locations/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/locations/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/locations/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/storage">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/pending">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/toggle-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/toggle-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/toggle-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/request-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/request-reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/request-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discount-cards/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discount-cards/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/discount-cards/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discount-cards/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discount-cards/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/discount-cards/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discount-cards/my-application/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discount-cards/my-application">> = Specific
  const handler = {} as typeof import("../../src/app/api/discount-cards/my-application/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/discount-cards/validate-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discount-cards/validate-id">> = Specific
  const handler = {} as typeof import("../../src/app/api/discount-cards/validate-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/evidence/[evidenceId]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/[evidenceId]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/evidence/[evidenceId]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fare-calculations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fare-calculations">> = Specific
  const handler = {} as typeof import("../../src/app/api/fare-calculations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geocode/forward/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode/forward">> = Specific
  const handler = {} as typeof import("../../src/app/api/geocode/forward/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geocode/reverse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode/reverse">> = Specific
  const handler = {} as typeof import("../../src/app/api/geocode/reverse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/[incidentId]/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents/[incidentId]/evidence">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/[incidentId]/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/[incidentId]/issue-ticket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents/[incidentId]/issue-ticket">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/[incidentId]/issue-ticket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/[incidentId]/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents/[incidentId]/resolve">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/[incidentId]/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/[incidentId]/take/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents/[incidentId]/take">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/[incidentId]/take/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/enforcer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents/enforcer">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/enforcer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/incidents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/api/incidents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations">> = Specific
  const handler = {} as typeof import("../../src/app/api/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/permits/[id]/renew/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/permits/[id]/renew">> = Specific
  const handler = {} as typeof import("../../src/app/api/permits/[id]/renew/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/permits/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/permits/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/permits/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/permits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/permits">> = Specific
  const handler = {} as typeof import("../../src/app/api/permits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routes/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes/calculate">> = Specific
  const handler = {} as typeof import("../../src/app/api/routes/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-coordinates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-coordinates">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-coordinates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/api/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracker/segment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracker/segment">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracker/segment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles/options">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/violations/history/[plateNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/violations/history/[plateNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/violations/history/[plateNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
