-- Generated by scripts/public-schema-cleanup.js
-- Review before execution. This file intentionally avoids CASCADE.
BEGIN;
DROP TABLE IF EXISTS "public"."authtoken_token";
DROP TABLE IF EXISTS "public"."dispatch_driveravailability";
DROP TABLE IF EXISTS "public"."dispatch_driverlocation";
DROP TABLE IF EXISTS "public"."dispatch_tripassignment";
DROP TABLE IF EXISTS "public"."django_session";
DROP TABLE IF EXISTS "public"."trips_cancellation";
DROP TABLE IF EXISTS "public"."trips_ratingreview";
DROP TABLE IF EXISTS "public"."users_discountusagelog";
DROP TABLE IF EXISTS "public"."users_incident";
DROP TABLE IF EXISTS "public"."dispatch_dispatchoffer";
DROP TABLE IF EXISTS "public"."dispatch_drivervehicle";
DROP TABLE IF EXISTS "public"."dispatch_driverprofile";
COMMIT;
