-- Generated by scripts/public-schema-cleanup.js
-- Review before execution. This file intentionally avoids CASCADE.
BEGIN;
DROP TABLE IF EXISTS "public"."auth_group_permissions";
DROP TABLE IF EXISTS "public"."django_admin_log";
DROP TABLE IF EXISTS "public"."django_migrations";
DROP TABLE IF EXISTS "public"."locations_servicearea";
DROP TABLE IF EXISTS "public"."token_blacklist_blacklistedtoken";
DROP TABLE IF EXISTS "public"."users_user_groups";
DROP TABLE IF EXISTS "public"."users_user_user_permissions";
DROP TABLE IF EXISTS "public"."token_blacklist_outstandingtoken";
DROP TABLE IF EXISTS "public"."auth_group";
DROP TABLE IF EXISTS "public"."auth_permission";
DROP TABLE IF EXISTS "public"."django_content_type";
COMMIT;
